#!/bin/zsh
export PATH="/usr/local/bin:/Users/songhabin/.npm-global/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
exec "/usr/local/bin/node" "/Users/songhabin/k-warning-check/native/codex-native-host.mjs"
